#!/bin/bash

set -e
[[ $DEBUG ]] && set -x

source ansible/hacking/env-setup
export PATH="$PWD/.binstubs:$PATH"

ansible/hacking/test-module -m ./docker_pull -a 'repo=foo/bar tag=latest'
python test/docker_pull_test.py
