#!/bin/bash
set -e

TOP=$(dirname $(dirname ${BASH_SOURCE[0]}))

cmd=$1
shift

case "$cmd" in
    pull)
        echo "---> not really docker pull $@"
        exit 0
    ;;
    images)
        cat "$TOP/tests/docker_images.txt"
        exit 0
    ;;
    *)
        echo NOPE
        exit 1
    ;;
esac
